//
// Created by mwiton on 17.05.16.
//

#ifndef SYSTEMY_OPERACYJNE_VALUES_H
#define SYSTEMY_OPERACYJNE_VALUES_H

#define KEY_BOARD 5678
#define KEY_DATA 6123
#define SIZE 231
#define COLUMN_SIZE 11
#define ROW_SIZE 21
#define MINES 50

#define PLAYERS 4
#define LENGTH_OF_DATA 4
#define IS_ACTIVE 0
#define STATE_OF_PLAYER 1
#define MOVEMENT 2
#define CORRECT_MOVEMENT 3
#define LAST_ID 4*LENGTH_OF_DATA+1

#endif //SYSTEMY_OPERACYJNE_VALUES_H
